<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Everywhere</AssemblyName>
    <EverywhereI18NNamespace>Everywhere.Linux.I18N</EverywhereI18NNamespace>
    <ApplicationTitle>Everywhere</ApplicationTitle>
    <SelfContained>true</SelfContained>
    <TargetFramework>$(TargetFrameworkPrefix)</TargetFramework>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationIcon>..\..\img\Everywhere.ico</ApplicationIcon>
    <IsDeploymentTarget>true</IsDeploymentTarget>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
    <PackageReference Include="Tmds.LibC" />
    <PackageReference Include="X11.Net" />
    <PackageReference Include="GirCore.GObject-2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Everywhere.Core\Everywhere.Core.csproj" />
    <ProjectReference Include="..\Everywhere.Mcp\Everywhere.Mcp.csproj" />
    <ProjectReference Include="..\Everywhere.I18N.Abstractions\Everywhere.I18N.Abstractions.csproj" />
    <ProjectReference Include="..\Everywhere.I18N.SourceGenerator\Everywhere.I18N.SourceGenerator.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="I18N\Strings*.resx"/>
    <AdditionalFiles Include="I18N\Strings*.resx"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\img\Everywhere.ico">
      <Link>Everywhere.ico</Link>
    </None>
    <Content Include="$(WatchdogExecutable)">
      <Link>Everywhere.Watchdog</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <Import Project="..\Build.Patches.targets" />

  <Import Project="..\Build.Watchdog.targets" />
  <Import Project="..\Build.OpenCliBundle.targets" />
</Project>
