// <auto-generated />
using System;
using Everywhere.Statistics.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Everywhere.Statistics.Database.Migrations
{
    [DbContext(typeof(StatisticsDbContext))]
    [Migration("20260625082156_Update_10_0_9")]
    partial class Update_10_0_9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Everywhere.Statistics.Database.DeviceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceGuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceGuid")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Everywhere.Statistics.Database.ModelInvocationEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssistantChatNodeId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CachedInputTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ChatContextId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GenerationSeconds")
                        .HasColumnType("REAL");

                    b.Property<long>("InputTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Purpose")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReasoningTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TurnEventId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatContextId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TurnEventId");

                    b.ToTable("ModelInvocationEvents");
                });

            modelBuilder.Entity("Everywhere.Statistics.Database.StatisticsMetadataEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("Everywhere.Statistics.Database.ToolInvocationEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChatContextId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FunctionName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModelInvocationEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginKey")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TurnEventId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatContextId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ModelInvocationEventId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TurnEventId");

                    b.ToTable("ToolInvocationEvents");
                });

            modelBuilder.Entity("Everywhere.Statistics.Database.TopicEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChatContextId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceId", "ChatContextId")
                        .IsUnique();

                    b.ToTable("TopicEvents");
                });

            modelBuilder.Entity("Everywhere.Statistics.Database.TurnEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssistantChatNodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChatContextId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserChatNodeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatContextId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceId");

                    b.ToTable("TurnEvents");
                });

            modelBuilder.Entity("Everywhere.Statistics.Database.VisualContextEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChatContextId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElementCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScreenshotCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TurnEventId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatContextId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TurnEventId");

                    b.ToTable("VisualContextEvents");
                });

            modelBuilder.Entity("Everywhere.Statistics.Database.ModelInvocationEventEntity", b =>
                {
                    b.HasOne("Everywhere.Statistics.Database.DeviceEntity", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Everywhere.Statistics.Database.ToolInvocationEventEntity", b =>
                {
                    b.HasOne("Everywhere.Statistics.Database.DeviceEntity", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Everywhere.Statistics.Database.TopicEventEntity", b =>
                {
                    b.HasOne("Everywhere.Statistics.Database.DeviceEntity", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Everywhere.Statistics.Database.TurnEventEntity", b =>
                {
                    b.HasOne("Everywhere.Statistics.Database.DeviceEntity", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Everywhere.Statistics.Database.VisualContextEventEntity", b =>
                {
                    b.HasOne("Everywhere.Statistics.Database.DeviceEntity", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
